### ISSUE TITLE
Master >> Main

### ISSUE THREAD

**Issue by MarkusTiede** [baloise/repository-template-java#15]

**Comment by arburk** [comment]
```
git branch -m master main
git push -u origin main
```
![image](https://user-images.githubusercontent.com/50652532/129025096-775c6ce2-609e-4555-9c2a-765005b77517.png)

Update Default Branch on GitHub & Protection Rules

```
git push origin --delete master
git remote set-head origin --auto
```
![image](https://user-images.githubusercontent.com/50652532/129026153-7c0018b3-3097-478b-a33f-e3dae38afc69.png)
